package org.example.model;

public enum UinversityType {
    DUMMY,
    STATE_DAYLY_UNIVERSITY,
    STATE_NIGHT_UNIVERSITY,
    AZAD_UNIVERSITY,
    NONPROFIT_UNIVERSITY,
    PAYAM_NOOR_UNIVERSITY,
    APPLIEDSCIENCES_UNIVERSITY,
    PARDIS_UNIVERSITY,
    NIGHT_UNIVERSITY;
}
